//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GivingActually_May.DataLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class GivingActuallyEntities : DbContext
    {
        public GivingActuallyEntities()
            : base("name=GivingActuallyEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<City> Cities { get; set; }
        public virtual DbSet<Tbl_Beneficiary> Tbl_Beneficiary { get; set; }
        public virtual DbSet<Tbl_BeneficiaryDetails> Tbl_BeneficiaryDetails { get; set; }
        public virtual DbSet<Tbl_Campaign> Tbl_Campaign { get; set; }
        public virtual DbSet<Tbl_CampaignDescription> Tbl_CampaignDescription { get; set; }
        public virtual DbSet<Tbl_CampaignDescriptionUpdates> Tbl_CampaignDescriptionUpdates { get; set; }
        public virtual DbSet<Tbl_CampaignDonation> Tbl_CampaignDonation { get; set; }
        public virtual DbSet<Tbl_CampaignTarget> Tbl_CampaignTarget { get; set; }
        public virtual DbSet<Tbl_CityDetails> Tbl_CityDetails { get; set; }
        public virtual DbSet<Tbl_Countries> Tbl_Countries { get; set; }
        public virtual DbSet<Tbl_GeoLocation> Tbl_GeoLocation { get; set; }
        public virtual DbSet<Tbl_Like> Tbl_Like { get; set; }
        public virtual DbSet<Tbl_ParentComment> Tbl_ParentComment { get; set; }
        public virtual DbSet<Tbl_PinCodeDetails> Tbl_PinCodeDetails { get; set; }
        public virtual DbSet<Tbl_States> Tbl_States { get; set; }
        public virtual DbSet<Tbl_Stories> Tbl_Stories { get; set; }
        public virtual DbSet<Tbl_StoriesAttachment> Tbl_StoriesAttachment { get; set; }
        public virtual DbSet<Tbl_Target> Tbl_Target { get; set; }
        public virtual DbSet<Tbl_UpdatesAttachment> Tbl_UpdatesAttachment { get; set; }
        public virtual DbSet<Tbl_User> Tbl_User { get; set; }
        public virtual DbSet<Tbl_UserAuthentication> Tbl_UserAuthentication { get; set; }
    
        public virtual int GetnearestCities(string lAT, string lONG)
        {
            var lATParameter = lAT != null ?
                new ObjectParameter("LAT", lAT) :
                new ObjectParameter("LAT", typeof(string));
    
            var lONGParameter = lONG != null ?
                new ObjectParameter("LONG", lONG) :
                new ObjectParameter("LONG", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GetnearestCities", lATParameter, lONGParameter);
        }
    }
}
