//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GivingActually_May.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Beneficiary
    {
        public int Id { get; set; }
        public Nullable<int> Btype { get; set; }
        public string BName { get; set; }
        public Nullable<int> BAge { get; set; }
        public Nullable<int> BGender { get; set; }
        public string BPhone { get; set; }
        public string BResidence { get; set; }
        public string DPName { get; set; }
        public string BGroupName { get; set; }
        public string BRelationship { get; set; }
        public Nullable<int> BMembers { get; set; }
        public int StoryId { get; set; }
        public bool Status { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public int Category { get; set; }
        public string IFSCcode { get; set; }
        public string BankName { get; set; }
        public string BankLocation { get; set; }
        public string AccountNo { get; set; }
        public string BankUserName { get; set; }
        public byte[] DP { get; set; }
    }
}
