//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GivingActually_May.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Stories
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Stories()
        {
            this.Tbl_Target = new HashSet<Tbl_Target>();
            this.Tbl_Target1 = new HashSet<Tbl_Target>();
            this.Tbl_Target2 = new HashSet<Tbl_Target>();
        }
    
        public int Id { get; set; }
        public int UserId { get; set; }
        public bool IsApprovedbyAdmin { get; set; }
        public string Title { get; set; }
        public string Story { get; set; }
        public bool Status { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public int Category { get; set; }
        public string Story_Expense { get; set; }
        public string Email { get; set; }
        public string storyDescription { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Target> Tbl_Target { get; set; }
        public virtual Tbl_User Tbl_User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Target> Tbl_Target1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Target> Tbl_Target2 { get; set; }
    }
}
